---
- name: Install hassos as a kvm virtual machine
  hosts: homeassistant
  become: True
  vars:
    # Desired hostname of Home Assistant
    - hassio_vm_name: "hassio.local"
    # Name of the network card that you will do a direct connection against on the host machine.
    - hassio_network_interface: "bridge0"
    # VM Storage location on your host
    - hassio_host_vm_storage: "/var/lib/libvirt/images/"
    # Location of the virtual appliance image
    - hassio_vm_qcow_file: "https://github.com/home-assistant/operating-system/releases/download/5.13/hassos_ova-5.13.qcow2.xz"
  tasks:
    - name: Install dependencies
      dnf:
        name:
          - epel-release
          - cockpit-machines
          - "@Virtualization Host"
        state: latest

    - name: Check if {{ hassio_vm_name }}.qcow2 exists on system
      stat:
        path: "{{ hassio_host_vm_storage }}{{ hassio_vm_name }}.qcow2"
      register: hassos_image

    - name: Download hassos qcow archive
      get_url:
        url: "{{ hassio_vm_qcow_file }}"
        dest: "{{ hassio_host_vm_storage }}{{ hassio_vm_name }}.qcow2.xz"
        owner: qemu
        group: qemu
      when: not hassos_image.stat.exists        

    - name: Uncompress hassos qcow archive
      command:
        cmd: "/usr/bin/xz --uncompress {{ hassio_host_vm_storage }}{{ hassio_vm_name }}.qcow2.xz"
        creates: "{{ hassio_host_vm_storage }}{{ hassio_vm_name }}.qcow2"
      when: not hassos_image.stat.exists        
      
    - name: Define and start "{{ hassos_vm_name }}" at boot
      virt:
        command: define
        xml: "{{ lookup('template', './template/homeassistant.xml.j2') }}"
        autostart: yes

    - name: Start the virtual machine "{{ hassos_vm_name }}"
      virt:
        name: "{{ hassio_vm_name }}"
        command: start
